### PR TITLE
feat: PublicKey+SelfKey `_put`, `_get`, `_delete` implementations with examples

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
## What I did
- [x] implement _put for SelfKey (encrypt data with selfEncryptionKey)
- [x] implement _get for SelfKey (decrypt data with selfEncryptionKey)
- [x] implement _delete for SelfKey
- [x] implement _put for PublicKey
- [x] implement _get for PublicKey
- [x] implement _delete for PublicKey
- [x] generate data signature when using _put for SelfKey (signSHA256withRSA with encryptionPrivateKey)
- [x] generate data signature when using _put for PublicKey (signSHA256withRSA with encryptionPrivateKey)
- [x] write PublicKeyPutExample
- [x] write PublicKeyDeleteExample
- [x] write PublicKeyPutExample
- [x] write SelfKeyPutExample
- [x] write SelfKeyGetExample
- [x] write SelfKeyDeleteExample
- [x] write SharedKeyPutExample
- [x] write SharedKeyGetSelfExample (get a self key created by you)
- [x] write SharedKeyGetOtherExample (get a self key created by another atSign)
- [x] write SharedKeyDeleteExample

## Some notable changes to achieve the above:

- [x] Created `EncryptionUtil.signSHA256RSA(String value, String privateKeyBase64)`:
Example of how it's used:
```java
String dataSignature = EncryptionUtil.signSHA256RSA("myValue123", keys.get(KeysUtil.encryptionPrivateKeyName)); // dataSignature for Metadata
atKey.metadata.dataSignature = dataSignature; // insert in Metadata
atClient.put(atKey); // write to secondary
```

- [x] `Keys.toString` now adds `cached:` to front if `Keys.Metadata.isCached` is `true`. 
- [x] Metadata.toString now adds `dataSignature:`, `isBinary:`, `isEncrypted:`

### CODE REVIEW

**Review by gkc — CHANGES_REQUESTED** [review]
Great work! Just one quibble - only Unit Tests should live under `test/java` (and names of all test files should end with `Test.java` - so please can you move all of the examples to a new examples directory `at_client/src/examples`

**Comment by JeremyTubongbanua** [comment]
## Some notable changes to achieve the above 18 checkboxes:

- [x] Created `EncryptionUtil.signSHA256RSA(String value, String privateKeyBase64)`:
Example of how it's used in AtClientImpl:
```java
String dataSignature = EncryptionUtil.signSHA256RSA("myValue123", keys.get(KeysUtil.encryptionPrivateKeyName)); // dataSignature for Metadata
atKey.metadata.dataSignature = dataSignature; // insert in Metadata
atClient.put(atKey); // write to secondary
```

- [x] `Keys.toString` now adds `cached:` to front if `Keys.Metadata.isCached` is `true`. 
- [x] `Metadata.toString` now has `dataSignature:`, `isBinary:`, `isEncrypted:`
- [x] `AtClientImpl.generateSIgnature(String value)` - generates a dataSignature for a given value, encrypt with encryptionPrivateKey

**Comment by JeremyTubongbanua** [comment]
The `_get` methods that I made for both `SelfKey` and `PublicKey` have a few concerns that I'd like address with you @gkc 

1. I'd like to make it low priority to fetch the metadata from the secondary server to update the cached AtKeys. (Everytime you use `_get` for both Self and Public, it will get the metadata via `llookup:meta` and update the AtKey object accordingly, but if an Exception is thrown for whatever reason, I don't want to make a big deal out of it and give the data that was found regardless). Right now, it is only implemented for PublicKey, but what do you think about this?

2. The code structure for the `_get(PublicKey)` method is kind of weird now that I look at it. Mostly this part:
```java
 // 2 scenarios
        // 1. look in own secondary server (including cached)
        // 2. look in another secondary server (via plookup)

        Secondary.Response rawResponse = null;

        // 1. look in own secondary
        String command = "llookup:" + key.toString();
        String metaCommand = "llookup:meta:" + key.toString();
        rawResponse = secondary.executeCommand(command, false);
        if(rawResponse.isError) {
            // try cached
            command = "llookup:cached:" + key.toString();
            metaCommand = "llookup:meta:cached:" + key.toString();
            rawResponse = secondary.executeCommand(command, false);
            if(rawResponse.isError) {
                // 2. try plookup
                command = "plookup:" + key.toString().replace("public:", "");
                metaCommand = "plookup:meta:" + key.toString().replace("public:", "");
                rawResponse = secondary.executeCommand(command, false);
                if(rawResponse.isError) {
                    throw new AtException("Failed to " + command + " : " + rawResponse.error);
                }
            }
        }
```

3. `_get(SelfKey)` checks if `isEncrypted` is true in the metadata to decrypt it, if it's false, we just return the `rawResponse.data`. Is the `isEncrypted` metadata reliable? Or should I just omit this metadata check and just aesDecrypt every single time?

**Comment by gkc** [comment]
Hi @VJag - please can you provide your thoughts on Jeremy's three questions above?

@JeremyTubongbanua I'll also carve out some time to review tomorrow. Re question 3 : right now, everything is encrypted (but in different ways for Self vs Shared of course) unless it is marked as public

Re point 2 : it's probably time to refactor to introduce patterns similar to those which have been adopted in the Dart client, where the put and get methods were simplified in part by introducing RequestTransformers and ResponseTransformers.

Re point 1 : I think when looking up the values, always use lookup:all (I think that's the syntax) which will get you all of the metadata as well as the value. Not sure what you mean re exceptions ... can you say a bit more about that?

**Comment by VJag** [comment]
**Ans Q1**: Use llookup. (I believe all is the default. If not we will pass it explicitly) It returns both data and metadata together. 

**Ans Q2**: We will use similar abstractions that we have used in Dart client

get {
	// Step 1: Validate if the key is valid
	// Step 2: Determine the verb that needs to be executed to fetch the data
	// Step 3: Parse the response
				- Deal with data:
				- Deal with error:
	// Step 4: Decrypt the data if it is encrypted
}


In Dart client:

1. AtClientValidation class contains the knowledge of what makes up a valid key and it does the validations
   Ex: await AtClientValidation.validateAtKey(atKey);	

2. VerbBuilder (and its subclasses) contains logic to form a verb to be sent over the wire

3. RequestTransformer<K, VerbBuilder> transforms a given a request/input into a VerbBuilder

4. ResponseTransformer transforms the response into a format that is presentable to the caller of the API
	
	- Understands data and error:
	- Performs JSON decode etc..
	- Decrypts
	 AtKeyDecryptionManager instantiates right decryption service based on the key



I suggest we follow the same pattern in the Java client too.

**Ans Q3**: Reliability of isEncrypted depends on how reliably we set it when doing a put. Let's assume that data is always encrypted as it is supposed to be decrypted based on what kind of key it is. Right now Dart client does not depend on that flag. Please check the subclasses of "AtKeyDecryption". Let us go ahead and decrypt without depending on the flag.

**Comment by JeremyTubongbanua** [comment]
Sounds like a plan. Thank you @VJag @gkc :)

**Pull request merged**
