### PR TITLE
feat: Various REPL enhancements

### PR DESCRIPTION
**Pull request by gkc**
**- What I did**
* feat: Various REPL enhancements

**- How I did it**
* feat: Various REPL enhancements
  * Coloured output to help see more clearly what's happening, improved output during startup
  * Improved help instructions
  * Removed /share command, which I found to be confusing as a returning user
  * Added bash script `at_client/src/main/scripts/atrepl` for convenience
* feat: `EncryptionUtil.aesDecryptFromBase64` now uses IV if supplied
* feat: AtClientImpl now knows to use an IV when decrypting notifications
* feat: Added a variation of `AtClient.getAtKeys` which allows you to request that getAtKeys **not** fetch metadata for each key (this can be very time-consuming for large scan results)
* refactor: extracted some duplicated code in AtClientImpl into a new `getLookupResponse` method
* fix: removed some unnecessary output to stdout / stderr

**- How to verify it**
* Tests pass
* Run the `<repo_root>/at_client/src/main/scripts/atrepl` script

**- Description for the changelog**
* feat: Various REPL enhancements

**- Additional context**
First toe in the water of using new encryption metadata ivNonce - this PR will decrypt notifications which were encrypted with an ivNonce, but the get and put methods in the AtClient do not yet understand or use an ivNonce

### CODE REVIEW

**Comment by JeremyTubongbanua** [comment]
@gkc How do I run `atrepl` correctly?

image

**Comment by gkc** [comment]
Bug in my script I guess

Should work if you run the script like src/main/scripts/atrepl

**Comment by gkc** [comment]
> Bug in my script I guess
> 
> Should work if you run the script like src/main/scripts/atrepl

Actually, strike that ... I don't get that error when I run the script

```
gary@gkc2019-2 scripts % ./atrepl -a @garycasey      
Connecting ... connected. Type '/help' to see help
@garycasey@ 
```

**Comment by gkc** [comment]
@JeremyTubongbanua what shell are you using? I'm using zsh
```
gary@gkc2019-2 ~ % echo $SHELL
/bin/zsh
```

**Comment by JeremyTubongbanua** [comment]
> @JeremyTubongbanua what shell are you using? I'm using zsh
> 
> ```
> gary@gkc2019-2 ~ % echo $SHELL
> /bin/zsh
> ```

```
jeremytubongbanua@Jeremys-M2-Air scripts % echo $SHELL
/bin/zsh
```

**Comment by JeremyTubongbanua** [comment]
I may have not been on the correct branch.

I am now though, I think.

git branch:
```
jeremytubongbanua@Jeremys-M2-Air scripts % git branch
* gkc-repl-20230419
  main
```

git remote -v
```
jeremytubongbanua@Jeremys-M2-Air scripts % git remote -v
gary    https://github.com/atsign-foundation/at_java.git (fetch)
gary    https://github.com/atsign-foundation/at_java.git (push)
```

git log (latest commit)
```
jeremytubongbanua@Jeremys-M2-Air scripts % git log
commit 9a8794013306565da74d0aaa6c7a2aa2e57e96f4 (HEAD -> gkc-repl-20230419, gary/gkc-repl-20230419)
Author: gkc <gary.casey@gmail.com>
Date:   Wed Apr 19 17:16:31 2023 +0100

    feat: the atrepl script
```

running `./atrepl`
```
jeremytubongbanua@Jeremys-M2-Air scripts % ./atrepl -a @jeremy_0
Error: Could not find or load main class org.atsign.client.cli.REPL
Caused by: java.lang.ClassNotFoundException: org.atsign.client.cli.REPL
```

**Comment by gkc** [comment]
Have you run mvn clean install ?

**Comment by JeremyTubongbanua** [comment]
> Have you run mvn clean install ?

That worked. Thank you!

(Comment for anyone running into this issue: I ran `mvn clean install` in the `at_client/` directory).

```zsh
jeremytubongbanua@Jeremys-M2-Air scripts % ./atrepl -a @jeremy_0
Connecting ... connected. Type '/help' to see help
@jeremy_0@ scan
  => data:["@6almond:phone_number_professional.buzzkey.atbuzz@jeremy_0","@6almond:professional.persona.atbuzz@jeremy_0","@6almond:shared_key@jeremy_0","@jeremy_0:address_personal.buzzkey.atbuzz@jeremy_0","@jeremy_0:allergies_health.buzzkey.atbuzz@jeremy_0","@jeremy_0:birthday_personal.buzzkey.atbuzz@jeremy_0","@jeremy_0:blood_group_health.buzzkey.atbuzz@jeremy_0","@jeremy_0:company_professional.buzzkey.atbuzz@jeremy_0","@jeremy_0:current_medication_health.buzzkey.atbuzz@jeremy_0","@jeremy_0:dob_health.buzzkey.atbuzz@jeremy_0","@jeremy_0:email_personal.buzzkey.atbuzz@jeremy_0","@jeremy_0:email_professional.buzzkey.atbuzz@jeremy_0","@jeremy_0:emergency_contact_health.buzzkey.atbuzz@jeremy_0","@jeremy_0:facebook_personal.buzzkey.atbuzz@jeremy_0","@jeremy_0:health.persona.atbuzz@jeremy_0","@jeremy_0:height_health.buzzkey.atbuzz@jeremy_0","@jeremy_0:instagram_personal.buzzkey.atbuzz@jeremy_0","@jeremy_0:linkedin_professional.buzzkey.atbuzz@jeremy_0","@jeremy_0:medical_conditions_health.buzzkey.atbuzz@jeremy_0","@jeremy_0:name_personal.buzzkey.atbuzz@jeremy_0","@jeremy_0:name_professional.buzzkey.atbuzz@jeremy_0","@jeremy_0:personal.persona.atbuzz@jeremy_0","@jeremy_0:phone_number_personal.buzzkey.atbuzz@jeremy_0","@jeremy_0:phone_number_professional.buzzkey.atbuzz@jeremy_0","@jeremy_0:professional.persona.atbuzz@jeremy_0","@jeremy_0:pronoun_personal.buzzkey.atbuzz@jeremy_0","@jeremy_0:pronoun_professional.buzzkey.atbuzz@jeremy_0","@jeremy_0:role_professional.buzzkey.atbuzz@jeremy_0","@jeremy_0:signing_privatekey@jeremy_0","@jeremy_0:twitter_personal.buzzkey.atbuzz@jeremy_0","@jeremy_0:webiste_professional.buzzkey.atbuzz@jeremy_0","@jeremy_0:weight_health.buzzkey.atbuzz@jeremy_0","@socccer0:test@jeremy_0","@soccer0:test@jeremy_0","atconnections.6almond.jeremy_0.at_contact.atbuzz@jeremy_0","atconnections.6almond.jeremy_0.at_contact.mospherepro@jeremy_0","cached:@jeremy_0:shared_key@6almond","cached:public:publickey@6almond","cached:public:publickey@soccer0","my_files_72bd8fee-a868-41e4-8601-9f0ff91036a5.mospherepro@jeremy_0","public:image.wavi@jeremy_0","public:publickey@jeremy_0","public:signing_publickey@jeremy_0","shared_key.6almond@jeremy_0","test@jeremy_0"]
```

**Comment by JeremyTubongbanua** [comment]
What work do you think could be done to make this more easily accessible? Like a Runnable JAR? @gkc

**Review by JeremyTubongbanua — APPROVED** [review]

**Pull request merged**
