### PR TITLE
fix: fix `cached:` prefix in Scan CLI

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
## What I did

Checked for `isCached` metadata and prepend `cached:` to the key name if `isCached==true`

### CODE REVIEW

**Review by gkc — APPROVED** [review]
LGTM

**Comment by gkc** [comment]
> LGTM

@JeremyTubongbanua What's your plan for the scan impl itself?

**Comment by JeremyTubongbanua** [comment]
> > LGTM
> 
> @JeremyTubongbanua What's your plan for the scan impl itself?

The `getAtKeys()` method returns a `List<AtKey>`, I don't think there's much I could do unless I modify the `.toString()` in `AtKey`

**Comment by gkc** [comment]
Yeah it's a bit tricky. Here's the way I think all of this *should* work: `cached` should not be a part of the key name. When `@bob` creates data which they share with `@alice`, and `@alice` secondary decides to cache that data (for whatever reason), then I believe there is zero value in prepending 'cached:' to the key name, since the very fact that `@bob`-owned data is stored on `@alice`'s secondary shows that it is cached.

@nickelskevin what do you think about this? This is relevant given our [recent & ongoing conversation](https://github.com/atsign-foundation/at_client_sdk/issues/744#issuecomment-1272375758) about overhauling caching behaviour generally

**Pull request merged**
