### PR TITLE
feat:Integrating Register CLI with registrar v3 API - NEW

### PR DESCRIPTION
**Pull request by srieteja**
Associated with issue https://github.com/atsign-foundation/at_server/issues/796
This PR has been created to track changes from https://github.com/atsign-foundation/at_java/pull/32 which got mixed up.

**- What I did**
- Integrating register cli with registrar v3
- New design for the register cli
- Tests for config_reader class
- Minor error corrections in documentation

### CODE REVIEW

**Review by gkc — CHANGES_REQUESTED** [review]
I pushed some changes to the branch, see latest commit. Please re-run your manual tests to verify I haven't broken anything.

One additional question - picocli latest version is 4.6.3 - any particular reason you are using version 4.5.2 ?

**Comment by srieteja** [comment]
> I pushed some changes to the branch, see latest commit. Please re-run your manual tests to verify I haven't broken anything.
> 
> One additional question - picocli latest version is 4.6.3 - any particular reason you are using version 4.5.2 ?

No specific reason for using that version. I have updated the version to 4.6.3

**Comment by gkc** [comment]
Great let me know when you've re-run tests and we can merge this PR

**Comment by srieteja** [comment]
I think version 3 of the registrar has not been released to prod yet. Do we still want this code out there ?

**Comment by gkc** [comment]
Ok let's wait until next week. Thank you!

**Comment by srieteja** [comment]
Sure, Gary. I'm sorry this task turned into a huge mess.

**Comment by gkc** [comment]
Nothing to apologize for! This stuff is important and takes time to get right.

**Comment by srieteja** [comment]
> Great let me know when you've re-run tests and we can merge this PR

I have re-run the tests and checked all use cases. They seem to hold. It's ready to merge.

**Review by gkc — APPROVED** [review]

**Pull request merged**
