### PR TITLE
refactor: Code restructuring, simplification, improved exception handling

### PR DESCRIPTION
**Pull request by gkc**
**- What I did**
refactor: Code restructuring, simplification, improved exception handling
Will need a major version change when we publish, but we should go all the way before we do so.

**- How I did it**
* Made AtException abstract
* Translate error codes from server into appropriate AtException subclass
* Created many new subclasses of AtException
* Removed NoSuchSecondaryException
* Improved exception handling; Secondary interface can now throw IOException as well as AtException
* Simplified LookupResponse by implementing a Jackson custom date deserializer in Metadata for the OffsetDateTime fields. Removed obsolete LlookupAllResponse
* Moved Metadata class up from Keys class to package level

**- How to verify it**
Tests pass

**- Description for the changelog**
refactor: Code restructuring, simplification, improved exception handling

### CODE REVIEW

**Review by JeremyTubongbanua — APPROVED** [review]

**Comment by JeremyTubongbanua** [comment]
Regarding this PR, a number of UMass students are getting this error after running this code.

Code:
image

Error:
image

**Comment by gkc** [comment]
Urgh, can you try to figure out what the problem is Jeremy? I don't have time until tomorrow morning

**Comment by gkc** [comment]
And also, 😳

**Comment by JeremyTubongbanua** [comment]
Already on it

**Comment by JeremyTubongbanua** [comment]
I've submitted a [PR](https://github.com/atsign-foundation/at_java/pull/111) @gkc

**Pull request merged**
