### PR TITLE
feat: Implemented  _getBinary(AtKey) and _put(AtKey, byte[]) in AtClientImpl.java

### PR DESCRIPTION
**Pull request by JayUpadhyay-8**
- What I did:- I have implemented these method: -
 _getBinary(SharedKey, byte[])
 _getBinary(SelfKey, byte[])
 _getBinary(PublicKey, byte[])
 _put(SharedKey, byte[]) in AtClientImpl.java
 _put(SelfKey, byte[]) in AtClientImpl.java
 _put(PublicKey, byte[]) in AtClientImpl.java

@TylerTrott @JeremyTubongbanua Please check the changes.

### CODE REVIEW

**Comment by JeremyTubongbanua** [comment]
Hey @JayUpadhyay-8, can you please make a PR to the `binary_impl` branch?

**Comment by JayUpadhyay-8** [comment]
I have updated the branch.

**Review by JeremyTubongbanua — CHANGES_REQUESTED** [review]
image

Maven is giving a compilation error. Is your trunk up to date with upstream?

**Comment by JayUpadhyay-8** [comment]
Yes I have checked my repo and it is up to date.

image

**Comment by JeremyTubongbanua** [comment]
Great work! I will test it on this branch now.

**Pull request merged**
