### PR TITLE
ci: add install to `maven-deploy.yml`

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
**- What I did**
- added `install` to the `maven-deploy.yml` workflow

**- How I did it**
- added "install" to the terminal command that is run

**- How to verify it**
See changes

**- Description for the changelog**
This will ensure that valid code is being pushed to central

### CODE REVIEW

**Review by gkc — APPROVED** [review]
Great job Jeremy

**Comment by gkc** [comment]
Oh ... maybe I spoke too soon...

This happens when I try to merge the branch:

image

**Review by gkc — CHANGES_REQUESTED** [review]
.

**Comment by JeremyTubongbanua** [comment]
@gkc Might be an issue with your GitHub app?

Can you please approve again and I can try merging :)

**Review by gkc — DISMISSED** [review]

**Review by gkc — APPROVED** [review]

**Pull request merged**
