### PR TITLE
feat: PrivateHiddenKey

### LINKED ISSUE #48: Implement _get, _put, _delete, PrivateHiddenKey
**Is your feature request related to a problem? Please describe.**
Implement `AtClientImpl.get(PrivateHiddenKey)` just like the rest of the AtKey types.

- [ ] _get(PrivateHiddenKey)
- [ ] _put(PrivateHiddenKey)
- [ ] _delete(PrivateHiddenKey)
- [ ] Implement new functionalities into the REPL

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
## What I did

- [x] _get PrivateHiddenKey
- [x] _put PrivateHiddenKey (String)
- [x] _delete PrivateHiddenKey

What's not done:

- getBinary PrivateHiddenKey
- put (byte[]) PrivateHiddenKey

closes #48

### CODE REVIEW

**Review by gkc — CHANGES_REQUESTED** [review]
LGTM but can you explain in the PR (1) what a private hidden key is and (2) how this implementation matches the implementation in the Dart client

**Comment by JeremyTubongbanua** [comment]
> LGTM but can you explain in the PR (1) what a private hidden key is and (2) how this implementation matches the implementation in the Dart client

Ah my fault, now that I am looking at the Dart client, PrivateKeys in the Dart client are prefixed with `privatekey:`... my code makes the keys prefixed with `_` because I thought privatekeys were the same as internal hidden keys..

**Comment by JeremyTubongbanua** [comment]
Should I just close this or refactor everything to `InternalKey` ?

Also I've tried to create my own privatekey in my secondary manually and it would not work @gkc any idea why?

```
@smoothalligator@ update:privatekey:test@smoothalligator fascin
org.atsign.common.AtException: error:AT0016-Invalid key : Key privatekey:test@smoothalligator is invalid
        at org.atsign.client.api.impl.secondaries.RemoteSecondary.executeCommand(RemoteSecondary.java:102)
        at org.atsign.client.api.impl.clients.AtClientImpl.executeCommand(AtClientImpl.java:385)
        at org.atsign.client.cli.REPL.repl(REPL.java:183)
        at org.atsign.client.cli.REPL.main(REPL.java:53)
Calling System.exit
```

Is it because I am only allowed to read private keys and/or modify pre-existing private keys?

**Comment by gkc** [comment]
Please set up some time to discuss this with @murali-shris ... it's important we retain consistency on the core concepts across SDKs

at_commons has classes & methods to determine what sort of key type a key is. That is canonical, Java SDK should be exactly aligned

**Comment by gkc** [comment]
Start by looking at AtKey.getKeyType in at_commons

**Comment by JeremyTubongbanua** [comment]
Thank you @gkc I will close for now because I do not think I did the correct approach.

**Pull request closed without merging**
